kind = "DojoContract"
class_hash = "0x14841a3f540d2b06e344d607fcee498ca0174337a63de4184f0fdfc5ba52f7a"
original_class_hash = "0x14841a3f540d2b06e344d607fcee498ca0174337a63de4184f0fdfc5ba52f7a"
base_class_hash = "0x0"
abi = "manifests/sepolia/base/abis/contracts/mancala-actions-5608e015.json"
reads = []
writes = []
init_calldata = []
tag = "mancala-actions"
systems = [
    "initialize_game_counter",
    "join_game",
    "create_private_game",
    "move",
    "forfeited",
    "request_restart_game",
    "restart_current_game",
]
manifest_name = "mancala-actions-5608e015"
